---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: check installed sudo package
      ansible.builtin.package:
        name: "sudo"
        state: present
      when:
        - ansible_distribution in [ "Debian", "Ubuntu" ]
      check_mode: true
      register: molecule_sudo_package
      failed_when: (molecule_sudo_package is changed) or (molecule_sudo_package is failed)

    - name: check /etc/sudoers.d/defaults file
      ansible.builtin.lineinfile:
        name: '/etc/sudoers.d/defaults'
        line: 'Defaults  mail_badpass'
        state: present
        owner: root
        group: root
        mode: '0440'
      check_mode: true
      register: molecule_sudo_defaults
      failed_when: (molecule_sudo_defaults is changed) or (molecule_sudo_defaults is failed)

    - name: check /etc/sudoers.d/users file
      ansible.builtin.lineinfile:
        name: '/etc/sudoers.d/users'
        line: 'user2 ALL=(ALL:ALL)  ALL'
        state: present
        owner: root
        group: root
        mode: '0440'
      check_mode: true
      register: molecule_sudo_user
      failed_when: (molecule_sudo_user is changed) or (molecule_sudo_user is failed)

    - name: check /etc/sudoers.d/aliases file
      ansible.builtin.lineinfile:
        name: '/etc/sudoers.d/aliases'
        line: 'User_Alias GROUPONE = user1, user2, user3'
        state: present
        owner: root
        group: root
        mode: '0440'
      check_mode: true
      register: molecule_sudo_aliases
      failed_when: (molecule_sudo_aliases is changed) or (molecule_sudo_aliases is failed)

    - name: check /etc/sudoers.d/groups file
      ansible.builtin.lineinfile:
        name: '/etc/sudoers.d/groups'
        line: 'sudogroup ALL=(ALL:ALL)  ALL'
        state: present
        owner: root
        group: root
        mode: '0440'
      check_mode: true
      register: molecule_sudo_groups
      failed_when: (molecule_sudo_groups is changed) or (molecule_sudo_groups is failed)
